# Generated by Django 4.2.15 on 2024-08-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0005_alter_test_created_by_alter_test_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
