# Generated by Django 4.2.15 on 2024-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0006_alter_test_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='test', to='QuestionBank.question'),
        ),
    ]
